markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments: true
plugins: ./_plugins
paginate: 8
permalink: /:year/:month/:day/:title/

safe: false

#站点基础配置
title: For The Best Thing In The World
subTitle: Cache.
description: 写东西的Cache
url: http://yonghaowu.github.io/
feed: /atom.xml

#菜单配置
nav:
  - text: 首页
    url: /
  - text: 技术
    url: /tech/
  - text: 生活
    url: /life/
  - text: 文章列表
    url: /archives/
  - text: 关于我
    url: /about/
  - text: 网站日志
    url: /logs/
  - text: 订阅
    url: /atom.xml

#theme config
themes: /themes/violet

#配置你喜欢的顶部背景图片
headimg:
  - item: http://gtms02.alicdn.com/tps/i2/T1PObnFqBdXXcryKEg-1280-200.jpg
  - item: http://gtms03.alicdn.com/tps/i3/T1U_YlFAlcXXbErygJ-2048-260.jpg
  - item: http://gtms04.alicdn.com/tps/i4/T1K0LLFvVbXXbErygJ-2048-260.jpg
  - item: http://gtms01.alicdn.com/tps/i1/T12DHKFx4bXXbErygJ-2048-260.jpg

#关注我
follow:

  - class: fa-github
    url: https://github.com/YongHaoWu
  - class: fa-twitter
    url: https://twitter.com/YongHao_Hu
  - class: fa-rss
    url: http://yonghaowu.github.io/atom.xml

#作者信息
author:
  name: YongHaoHu
  link: https://www.linkedin.com/in/yonghaohu
  img: 

#评论信息
disqus:
  config: false
  id: piznblog

duoshuo:
  config: true
  id: yonghaohu
